/*
 * ADC.c
 *
 *  Created on: Feb 3, 2023
 *      Author: Lenovo
 */
#include "Types.h"

#include "GPIO.h"

#include "ADC.h"
#include "ADC_Types.h"
#include "ADC_HW.h"
#include "ADC_Config.h"

void (*ADC_Ptr_CallBack)(void);

void ADC_Init				(void)
{

	//Voltage options
#if	  ADC_VREF_CONFIG==INTERNAL_AREF
	ADC->ADMUX.BITS.REFS0=LOW;
	ADC->ADMUX.BITS.REFS1=LOW;
#elif ADC_VREF_CONFIG==AVCC_WITH_EXT_CAP
	ADC->ADMUX.BITS.REFS0=HIGH;
	ADC->ADMUX.BITS.REFS1=LOW;
#elif ADC_VREF_CONFIG==INTERNAL_2_56_WITH_CAP
	ADC->ADMUX.BITS.REFS0=HIGH;
	ADC->ADMUX.BITS.REFS1=HIGH;
#endif
	//Adjusting data
#if	  ADC_BIT_ADJUST==RIGHT_ADJUST
	ADC->ADMUX.BITS.ADLAR=LOW;
#elif ADC_BIT_ADJUST==LEFT_ADJUST
	ADC->ADMUX.BITS.ADLAR=HIGH;
#else
	#error "Error in ADC VREF Options"
#endif
	//Set Prescaler
#if   ADC_PRESCALER==ADC_PRESCALER_2
	ADC->ADCSRA.BITS.ADPS0=LOW;
	ADC->ADCSRA.BITS.ADPS1=LOW;
	ADC->ADCSRA.BITS.ADPS2=LOW;
#elif ADC_PRESCALER==ADC_PRESCALER_4
	ADC->ADCSRA.BITS.ADPS0=LOW;
	ADC->ADCSRA.BITS.ADPS1=HIGH;
	ADC->ADCSRA.BITS.ADPS2=LOW;
#elif ADC_PRESCALER==ADC_PRESCALER_8
	ADC->ADCSRA.BITS.ADPS0=HIGH;
	ADC->ADCSRA.BITS.ADPS1=HIGH;
	ADC->ADCSRA.BITS.ADPS2=LOW;
#elif ADC_PRESCALER==ADC_PRESCALER_16
	ADC->ADCSRA.BITS.ADPS0=LOW;
	ADC->ADCSRA.BITS.ADPS1=LOW;
	ADC->ADCSRA.BITS.ADPS2=HIGH;
#elif ADC_PRESCALER==ADC_PRESCALER_32
	ADC->ADCSRA.BITS.ADPS0=HIGH;
	ADC->ADCSRA.BITS.ADPS1=LOW;
	ADC->ADCSRA.BITS.ADPS2=HIGH;
#elif ADC_PRESCALER==ADC_PRESCALER_64
	ADC->ADCSRA.BITS.ADPS0=LOW;
	ADC->ADCSRA.BITS.ADPS1=HIGH;
	ADC->ADCSRA.BITS.ADPS2=HIGH;
#elif ADC_PRESCALER==ADC_PRESCALER_128
	ADC->ADCSRA.BITS.ADPS0=HIGH;
	ADC->ADCSRA.BITS.ADPS1=HIGH;
	ADC->ADCSRA.BITS.ADPS2=HIGH;
#else
	#error "Error in ADC Prescaler Options"
#endif
	//ADC Enable
	ADC->ADCSRA.BITS.ADEN=HIGH;//ADC Enable
}
void ADC_InitInterrupt		(void)
{
	//Voltage options
#if	  ADC_VREF_CONFIG==INTERNAL_AREF
	ADC->ADMUX.BITS.REFS0=LOW;
	ADC->ADMUX.BITS.REFS1=LOW;
#elif ADC_VREF_CONFIG==AVCC_WITH_EXT_CAP
	ADC->ADMUX.BITS.REFS0=HIGH;
	ADC->ADMUX.BITS.REFS1=LOW;
#elif ADC_VREF_CONFIG==INTERNAL_2_56_WITH_CAP
	ADC->ADMUX.BITS.REFS0=HIGH;
	ADC->ADMUX.BITS.REFS1=HIGH;
#endif
	//Adjusting data
#if	  ADC_BIT_ADJUST==RIGHT_ADJUST
	ADC->ADMUX.BITS.ADLAR=LOW;
#elif ADC_BIT_ADJUST==LEFT_ADJUST
	ADC->ADMUX.BITS.ADLAR=HIGH;
#else
	#error "Error in ADC VREF Options"
#endif
	//Set Prescaler
#if   ADC_PRESCALER==ADC_PRESCALER_2
	ADC->ADCSRA.BITS.ADPS0=LOW;
	ADC->ADCSRA.BITS.ADPS1=LOW;
	ADC->ADCSRA.BITS.ADPS2=LOW;
#elif ADC_PRESCALER==ADC_PRESCALER_4
	ADC->ADCSRA.BITS.ADPS0=LOW;
	ADC->ADCSRA.BITS.ADPS1=HIGH;
	ADC->ADCSRA.BITS.ADPS2=LOW;
#elif ADC_PRESCALER==ADC_PRESCALER_8
	ADC->ADCSRA.BITS.ADPS0=HIGH;
	ADC->ADCSRA.BITS.ADPS1=HIGH;
	ADC->ADCSRA.BITS.ADPS2=LOW;
#elif ADC_PRESCALER==ADC_PRESCALER_16
	ADC->ADCSRA.BITS.ADPS0=LOW;
	ADC->ADCSRA.BITS.ADPS1=LOW;
	ADC->ADCSRA.BITS.ADPS2=HIGH;
#elif ADC_PRESCALER==ADC_PRESCALER_32
	ADC->ADCSRA.BITS.ADPS0=HIGH;
	ADC->ADCSRA.BITS.ADPS1=LOW;
	ADC->ADCSRA.BITS.ADPS2=HIGH;
#elif ADC_PRESCALER==ADC_PRESCALER_64
	ADC->ADCSRA.BITS.ADPS0=LOW;
	ADC->ADCSRA.BITS.ADPS1=HIGH;
	ADC->ADCSRA.BITS.ADPS2=HIGH;
#elif ADC_PRESCALER==ADC_PRESCALER_128
	ADC->ADCSRA.BITS.ADPS0=HIGH;
	ADC->ADCSRA.BITS.ADPS1=HIGH;
	ADC->ADCSRA.BITS.ADPS2=HIGH;
#else
	#error "Error in ADC Prescaler Options"
#endif
	//ADC Enable
	ADC->ADCSRA.BITS.ADEN=HIGH;//ADC Enable
	ADC->ADCSRA.BITS.ADIE=HIGH;//ADC Int enable
}
void ADC_SelectChannel				(ADC_Channel Channel)
{
	//Mask 5 LSB Data
	Channel&=0x07;
	//Mask 5 MUX bits
	ADC->ADMUX.ALLREG&=0xE0;
	ADC->ADMUX.ALLREG |=Channel;
}

u16 ADC_StartConv			(ADC_Channel Channel)
{
	u16 Data=0;
	ADC_SelectChannel(Channel);
	//Start Conversion
	ADC->ADCSRA.BITS.ADSC=HIGH;
	//wait till the flag rises
	while(ADC->ADCSRA.BITS.ADIF==0);
#if ADC_BIT_ADJUST==RIGHT_ADJUST
	Data= ADC->ADCDR;
#elif ADC_BIT_ADJUST==LEFT_ADJUST
	Data=(ADC->ADCDR>>6);
#else
	#error "Error in ADC VREF Options"
#endif
	return Data;
}

u16 ADC_StartConvInterrupt			(ADC_Channel Channel)
{
	u16 Data=0;
	ADC_SelectChannel(Channel);
	//Start Conversion
	ADC->ADCSRA.BITS.ADSC;
#if ADC_BIT_ADJUST==RIGHT_ADJUST
	Data=(u16) ADC->ADCDR;
#elif ADC_BIT_ADJUST==LEFT_ADJUST
	Data=(ADC->ADCDR>>6);
#else
	#error "Error in ADC VREF Options"
#endif
	return Data;
}

u16 ADC_Read(void)
{
	 return ADC->ADCDR;
}

void ADC_SetCallBackFun(void (*ADC_PtrFun_CallBack)(void))
{
	ADC_Ptr_CallBack=ADC_PtrFun_CallBack;
}

void __vector_16(void)	__attribute__((signal));
void __vector_16(void)
{
	ADC_Ptr_CallBack();
}

