/*
 * ADC_Config.h
 *
 *  Created on: Feb 3, 2023
 *      Author: Lenovo
 */

#ifndef MCAL_ADC_INCLUDES_ADC_CONFIG_H_
#define MCAL_ADC_INCLUDES_ADC_CONFIG_H_

//CONFIGS
#define ADC_VREF_CONFIG AVCC_WITH_EXT_CAP
/*Vref Options
 *1-INTERNAL_AREF
 *2-AVCC_WITH_EXT_CAP
 *3-INTERNAL_2_56_WITH_CAP
 */
#define ADC_BIT_ADJUST RIGHT_ADJUST
/*Adjust options
 * 1-RIGHT_ADJUST
 * 2-LEFT_ADJUST
 */
#define ADC_PRESCALER	ADC_PRESCALER_128
/*Prescaler Options
 * 1-ADC_PRESCALER_2
 * 2-ADC_PRESCALER_4
 * 3-ADC_PRESCALER_8
 * 4-ADC_PRESCALER_16
 * 5-ADC_PRESCALER_32
 * 6-ADC_PRESCALER_64
 * 7-ADC_PRESCALER_128
 */


#endif /* MCAL_ADC_INCLUDES_ADC_CONFIG_H_ */
