/*
 * USART_Config.h
 *
 *  Created on: Feb 3, 2023
 *      Author: Barakat
 */

#ifndef MCAL_USART_INCLUDES_USART_CONFIG_H_
#define MCAL_USART_INCLUDES_USART_CONFIG_H_

/* MODE_SELECT OPTIONS
 * 1-ASYNCHRONOUS_MODE
 * 2-SYNCHRONOUS_MODE
 */
#define MODE_SELECT	 ASYNCHRONOUS_MODE

/* PARITY_MODE OPTIONS
 * 1-PARITY_DISABLED_MODE
 * 2-PARITY_EVEN_MODE
 * 3-PARITY_ODD_MODE
 */
#define PARITY_MODE	 PARITY_DISABLED_MODE

/*STOP_BIT_MODE OPTIONS
 * 1-ONE_STOP_BIT_MODE
 * 2-TWO_STOP_BIT_MODE
 */
#define STOP_BIT_MODE	ONE_STOP_BIT_MODE

/*DATA_MODE OPTIONS
 * 1-DATA_5BITS
 * 2-DATA_6BITS
 * 3-DATA_7BITS
 * 4-DATA_8BITS
 * 5-DATA_9BITS
 */
#define DATA_MODE	DATA_8BITS
#define BAUD_RATE	103
#endif /* MCAL_USART_INCLUDES_USART_CONFIG_H_ */
